### PR TITLE
Complete missing sections in Q# grammar

### PR DESCRIPTION
**Pull request by bamarsha**
There were two different styles used for aligning the `.`, so I wasn't sure which one to use... personally, I prefer aligning `.` next to the case name without a space.

### CODE REVIEW

**Comment by bamarsha** [comment]
When I run `TestQSharp` on this file: https://github.com/microsoft/QuantumKatas/blob/main/BasicGates/Tests.qs
I get this error message:

> Fatal error: exception Failure("lexing: empty token")

**Comment by bamarsha** [comment]
Adding an interpolated string case seems to fix it (but I still wish the error message was better).

**Comment by k4rtik** [comment]
Thanks for a quick fix, I think we should add some samples here, those that work and those that we would like to work (but currently don't). There were several that fail with `Fatal error: exception ParQSharp.MenhirBasics.Error`, but I pushed a few that worked or failed more specifically. An example:
```
./TestQSharp qs-samples/Types.qs
Parse error at 39.40-39.41
```

PS: Created issue #2 for fixing older sample files. 


EDIT (May 11, 2022). It works now:

```
$  ./TestQSharp qs-samples/Libraries/Standard/Types.qs 
[Abstract syntax]

Prog ([NDec (QQual (QIdent "Microsoft.Quantum.Preparation"), [NSOp (QQual (QIdent "Microsoft.Quantum.Arithmetic")); NSTy (DPrefix ([], AEmpty), Ident "MixedStatePreparation", UTTpl ([TTIName (NItem (Ident "Requirements", TQNm (QUnqual (Ident "MixedStatePreparationRequirements")))); TTIName (NItem (Ident "Norm", TDbl)); TTIName (NItem (Ident "Prepare", TTpl ([TOp (TTpl ([TQNm (QUnqual (Ident "LittleEndian")); TArr (TQbit); TArr (TQbit)]), TUnit, CIs (CEPlus (CEAdj, CECtl)))])))])); NSTy (DPrefix ([], AEmpty), Ident "MixedStatePreparationRequirements", UTTpl ([TTIName (NItem (Ident "NTotalQubits", TInt)); TTIUTyp (UTTpl ([TTIName (NItem (Ident "NIndexQubits", TInt)); TTIName (NItem (Ident "NGarbageQubits", TInt))]))]))])])

[Linearized tree]

namespace Microsoft.Quantum.Preparation
{
  open Microsoft.Quantum.Arithmetic;
  newtype MixedStatePreparation = (Requirements : MixedStatePreparationRequirements, Norm : Double, Prepare : ((LittleEndian, Qubit [], Qubit []) => Unit is Adj + Ctl));
  newtype MixedStatePreparationRequirements = (NTotalQubits : Int, (NIndexQubits : Int, NGarbageQubits : Int));
}

```

**Comment by k4rtik** [comment]
> An example:
> 
> ```
> ./TestQSharp qs-samples/Types.qs
> Parse error at 39.40-39.41
> ```

The root cause of this problem is the conflict between 
`UTTpl  . UType ::= "(" [TyTplItem] ")";`
and
`TTpl  . Typ ::= "(" [Typ] ")";`


EDIT (May 11, 2022): see previous comment, this may not be accurate anymore

**Comment by k4rtik** [comment]
## Working tests from qs-samples
```
# Contests
## Summer 2018 
summer18/b3.qs
summer18/b4.qs
summer18/c1.qs
summer18/c2.qs
summer18/d3.qs

## Winter 2019 Contest
winter19/a1.qs
winter19/b1.qs
winter19/d1.qs
winter19/d2.qs
winter19/d3.qs
winter19/d5.qs

# Katas
BasicGates.qs
BoundedKnapsack.qs
CHSHGame.qs
JointMeasurements.qs
PhaseEstimation.qs
QEC_BitFlipCode.qs
SimonsAlgorithm.qs
SuperdenseCoding.qs
Teleportation.qs

# Libraries

## Numerics
Addition.qs
ArithmeticWrappers.qs
Comparison.qs
Convert.qs
Facts.qs
Inversion.qs
Polynomial.qs
Reciprocal.qs
Types.qs

## Chemistry
SystemTestBlockEncoding.qs
Utils.qs

## MachineLearning
Classification.qs
ClassificationTests.qs
IrisDataset.qs
NamespaceInfo.qs
TypesTests.qs
ValidationTests.qs
WineDataset.qs

## Standard
5QubitCode.qs
7QubitCode.qs
Algorithms.qs
Allows.qs
AllowTests.qs
All.qs
AmplitudeAmplification.qs
ANDTests.qs
Any.qs
ApplyDual.qs
ApplyIf.qs
ApplyMultiControlled.qs
ApplyMultiControlledTests.qs
Apply.qs
ApplyRepeatedOver.qs
ApplyRepeatedOverTests.qs
ApplyReversed.qs
ApplyToArray.qs
ApplyToEachIndex.qs
ApplyToEach.qs
ApplyToElement.qs
ApplyToFirst.qs
ApplyToPartition.qs
Arithmetic.qs
ArithmeticTests.qs
Asserts.qs
Bind.qs
BitFlipCode.qs
Bitwise.qs
BlockEncoding.qs
BooleanOperators.qs
BuildConfiguration.qs
CControlled.qs
CombinatorTests.qs
CommonGateTests.qs
Comparators.qs
Comparisons.qs
ComparisonTests.qs
Complex.qs
Compose.qs
Constants.qs
ControlledOnBitString.qs
ControlledOnBitStringTests.qs
ConversionTests.qs
Convert.qs
Curry.qs
Delay.qs
Deprecated.qs
Diagnostics.qs
Distinguishability.qs
DistinguishabilityTests.qs
Dump.qs
DumpTests.qs
Enumeration.qs
EqualA.qs
Fold.qs
GroupProduct.qs
Increment.qs
Internal.qs
Iterative.qs
Mixed.qs
NamespaceInfo.qs
OperationPow.qs
Operators.qs
Pairs.qs
PairTests.qs
PauliTests.qs
ProcessTomography.qs
QcvvTests.qs
QFTTests.qs
Random.qs
Range.qs
Reference.qs
Reflections.qs
ReflectionTests.qs
Repeat.qs
RepeatTests.qs
ResetTests.qs
RestrictedToSubregister.qs
Robust.qs
Search.qs
SingleQubitCliffordTests.qs
Sorted.qs
SortedTests.qs
Techniques.qs
TransformationBased.qs
Trotter.qs
TypeConversionTests.qs
Types.qs
UniformSuperposition.qs
Unique.qs
UniqueTests.qs
UnitaryDecompositionTest.qs
Univariate.qs
Utils.qs
With.qs
```

Various errors on other tests.

I believe summer18 and summer19 tests will not pass as syntax has changed, but it might be worth manually looking at them to update the syntax. The tests in the Standard directory are probably the most important. Here are some stats:

|  Dir 	|  Passed 	| Total  	|
|---	|---	|---	|
|  Katas 	|  9 	|  23 	|
|   Numerics	|   9	|   15	|
|  Chemistry 	|   2	|   17	|
|   MachineLearning	|   7	|  16 	|
|   Standard	|   96	|   160	|

**Comment by k4rtik** [comment]
Hi @samarsha, I have switched to Kesha's samples directory and added a bit of analysis above. Hope this helps take this PR forward.

Let me know if I can help with anything to make it faster.

**Comment by k4rtik** [comment]
Reference for Q# Grammar: https://github.com/microsoft/qsharp-language/tree/main/Specifications/Language/5_Grammar

Q# Samples: https://github.com/LambdaQs/qsharp-samples

**Comment by k4rtik** [comment]
Development is moved to https://github.com/LambdaQs/arrays, closing.

See https://github.com/LambdaQs/arrays/issues/3 and https://github.com/LambdaQs/arrays/issues/4 for missing pieces.

**Pull request closed without merging**
